[package]
name = "xoev-xwasser"
version = "0.2.1"
authors = ["H & D GmbH Open Source <contact-oss@h-d-gmbh.de>"]
edition = "2021"
description = "XOEV XWasser XML Standard"
license = "MIT"
repository = "https://github.com/hd-gmbh-dev/xoev-xwasser-rs.git"
categories = []
keywords = []

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wasm"]
wasm = ["dep:wasm-bindgen", "dep:tsify"]

[dependencies]
raxb = "0.3.7"
serde = { version = "1.0.203", features = ["derive"] }

wasm-bindgen = { version = "0.2.84", optional = true }
tsify = { version = "0.4.5", features = ["js"], optional = true }

[dev-dependencies]
serde_json = "1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
