[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.2.2+0.2.1"
description = """
"XOEV XWasser XML Standard"
"""
rust-version = "1.78.0"
authors = ["H & D GmbH Open Source <contact-oss@h-d-gmbh.de>"]
license = "MIT"
repository = "https://github.com/hd-gmbh-dev/xoev-xwasser-rs"
categories = []
keywords = []

[workspace.dependencies]
xoev-xwasser-derive-rs = { version = "0.2.2+0.2.1", path = "crates/derive" }

[package]
name = "xoev-xwasser"
edition.workspace = true
version.workspace = true
description.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["schema", "trace"]
trace = []
wasm = ["dep:wasm-bindgen", "dep:tsify"]
schema = [
    "dep:rust-embed",
    "dep:raxb-validate",
    "dep:raxb-xmlschema",
    "dep:anyhow",
]

[dependencies]
# raxb = "0.3.7"

xoev-xwasser-derive-rs.workspace = true
anyhow = { version = "1", optional = true }
rust-embed = { version = "8.5.0", optional = true }
raxb = { path = "../raxb/crates/raxb", features = ["trace"] }
raxb-validate = { path = "../raxb/crates/raxb-validate", optional = true }
raxb-xmlschema = { path = "../raxb/crates/raxb-xmlschema", optional = true }

serde = { version = "1.0.203", features = ["derive"] }

wasm-bindgen = { version = "0.2.84", optional = true }
tsify = { version = "0.4.5", features = ["js"], optional = true }

[build-dependencies]
raxb-xmlschema-build = { path = "../raxb/crates/raxb-xmlschema-build" }
anyhow = "1"

[dev-dependencies]
raxb-xmlschema-build = { path = "../raxb/crates/raxb-xmlschema-build" }
serde_json = "1"
anyhow = "1"
test-log = { version = "0.2.16", default-features = false, features = ["trace", "color"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
