[package]
name = "xoev-xwasser"
version = "0.2.1"
authors = ["H & D GmbH Open Source <contact-oss@h-d-gmbh.de>"]
edition = "2021"
description = "XOEV XWasser XML Standard"
license = "MIT"
repository = "https://github.com/hd-gmbh-dev/xoev-xwasser-rs.git"
categories = []
keywords = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
tsify = { version = "0.4.5", features = ["js"] }
raxb = "0.3.7"
serde = { version = "1.0.203", features = ["derive"] }
derive_builder = "0.20.0"

[dev-dependencies]
serde_json = "1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
