[package]
name = "xwasser-rs"
version = "0.1.0"
authors = ["Jürgen Seitz <juergen.seitz@h-d-gmbh.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
tsify = { version = "0.4.5", features = ["js"] }
raxb = "0.3.7"
serde = { version = "1.0.203", features = ["derive"] }
derive_builder = "0.20.0"

[dev-dependencies]
serde_json = "1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
