name: Build and test

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.78.0
      - name: get-cmake
        uses: lukka/get-cmake@latest
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.12.1"
      - uses: pnpm/action-setup@v4
      - name: Check
        run: |
          rustup component add clippy
          cargo clippy --no-deps
      - name: Build
        run: cargo build --features schema,trace --release
      - name: Test Rust
        run: cargo test --features schema,trace
      - name: Build WASM
        run: |
          wasm-pack build --release --target web --reference-types --weak-refs --features wasm
          cp target/schemas/out/*.xsdb pkg/xwasser-v052.xsdb.bin
          cp package.tmp.json pkg/package.json
      - name: Test WASM
        run: |
          pnpm install
          pnpm test
      - name: Archive NPM package
        uses: actions/upload-artifact@v4
        with:
          name: xoev-xwasser-pkg
          path: ./pkg
  publish:
    if: startsWith( github.ref, 'refs/tags/v' )
    uses: ./.github/workflows/publish.yaml
    needs: build-and-test
    secrets: inherit
