name: Publish to crates.io and registry.npmjs.org

on:
  workflow_call:
    secrets:
      CRATES_TOKEN:
        required: true
      BOT_GITHUB_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: dtolnay/rust-toolchain@1.81.0
    - name: get-cmake
      uses: lukka/get-cmake@latest
    - name: Publish to crates.io.
      run: |
        cargo publish --token ${CRATES_TOKEN} -p xoev-xwasser-derive
        cargo publish --token ${CRATES_TOKEN} -p xoev-xwasser-codelists
        cargo publish --token ${CRATES_TOKEN} -p xoev-xwasser
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Download NPM artifact
      uses: actions/download-artifact@v4
      with:
        name: xoev-xwasser-pkg
        path: pkg
    - run: npm publish --provenance --access public
      working-directory: ./pkg
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Download NPM Web artifact
      uses: actions/download-artifact@v4
      with:
        name: xoev-xwasser-pkg-web
        path: pkg
    - run: npm publish --provenance --access public
      working-directory: ./pkg
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
      name: Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false
